language: ruby
before_install:
  - gem install bundler
script:
  - bundle exec rspec ./spec/
rvm:
  - 2.2.6
  - 2.3.4
  - 2.4.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
